#!/usr/bin/env bash
# check-identity.sh — keep OEM, customer and person identity out of a repository.
#
# THE SINGLE DENYLIST, and it lives IN the repo it protects so a clone carries it —
# HASHED (see the denylist block below), so the guard blocks identifiers without naming
# them. Four callers share it and therefore cannot drift apart about what counts:
#
#   .githooks/pre-commit          --staged, refusing new entry at the moment it would
#                                 enter history (install: git config core.hooksPath .githooks)
#   .githooks/commit-msg          --message, doing the same for the commit MESSAGE, which is
#                                 history too and which a file-content scan cannot see
#   tests/test_repo_identity.py   the same sweep as a TEST, so a fresh clone is guarded
#                                 even before anyone runs the install step; it also runs
#                                 --history against a named baseline of known offenders
#   a scheduled adversarial audit  calling the same script from outside the repo
#
# WHY commit-time and not push-time: the working copies auto-push on commit, so there is
# no "clean it before I push" window. `git commit --no-verify` bypasses the hook, which is
# not a defect to engineer around; it is why the test and the scheduled sweep exist behind it.
#
# CLEAN AT CREATION, which is the whole point. Git history travels with a repository and
# cannot be selectively un-published later, so anything that reaches history has to come out
# afterwards with a filter-repo purge. The exposure this pattern was built after needed three
# passes. Keeping the tree clean at the moment of the commit is the cheap version of that.
#
# ESCAPE HATCH: a line carrying `oem-allow: <reason>` is permitted. That is how a test can
# name an identifier in order to assert its absence, and it makes every real identifier a
# deliberate, reviewable choice rather than an accident.
#
# In a commit MESSAGE the marker is a trailer and covers the WHOLE message, not its own
# line. Per-line would be unusable there: the identifier is normally in the subject while
# the trailer sits at the bottom, so a per-line rule would refuse the very message the
# trailer exists to permit. It stays reviewable because `git log` shows the trailer.
#
# Usage: check-identity.sh [--staged | --message <file> | --history [<range>] |
#                           --file <path> [--ignore-allow]]
# Exit 0 clean, 1 offender found, 2 misuse. The contract is identical in every mode.

set -uo pipefail

REPO="${HARNESS_REPO:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

# --- the HASHED denylist (the whole denylist, since 2026-08-24) -------------------
#
# Tokens that must not appear in tracked core do not appear in this guard either: a
# guard that names what it blocks would itself be the leak. It began with maker names
# (a real maker is named only once it has authorised that use) and now covers every
# category: part numbers, model families, document identifiers, persons and customer
# identity. The tokens live in a PRIVATE,
# gitignored, human-editable source (tools/identity-denylist-private.txt, which also
# documents each category) and the tracked file carries only '<length> <sha256>' pairs,
# GENERATED by tools/generate-identity-hashes.sh, never hand-written.
#
# Matching is by TOKEN PREFIX: each token is lowercased and its prefix at each listed
# entry length is hashed and compared, so one entry covers an open-ended family
# (a part-number stem, a model family). Entries shorter than the generator's floor are
# refused at generation time. What this cannot see: an identifier buried MID-token with
# a novel stem, an accepted cost of hashing, verified when the denylist is written by
# checking that no current identifier has that shape. Hashing defeats
# READING, not guessing: a dictionary word can be hashed by anyone who suspects it.
# Acceptable because the posture is commercial courtesy, not secrecy.
#
# python3 is required for the hashing; the repo's own tests already require it.
HASHES="${IDENTITY_HASHES:-$REPO/tools/identity-denylist.hashes}"

if [ ! -f "$HASHES" ]; then
  echo "check-identity: FATAL, the generated hash denylist is MISSING: $HASHES" >&2
  echo "A guard that silently passes without its denylist is worse than no guard," >&2
  echo "because it reports success. Regenerate it from the private source:" >&2
  echo "    bash tools/generate-identity-hashes.sh" >&2
  exit 2
fi

hits=0
allowed=0
ALLOWED_LINES=""

note_allowed() {  # path, lineno, text — enumerate every oem-allow exemption, never
                  # exempt silently: an invisible exemption is how the marker becomes a
                  # way to mute the check.
  local trimmed
  trimmed=$(printf '%s' "$3" | sed 's/^[[:space:]]*//' | cut -c1-100)
  ALLOWED_LINES="${ALLOWED_LINES}  allowed  $1:$2
           ${trimmed}
"
  allowed=$((allowed + 1))
}

# Hashed-token scan. stdin: records "location<TAB>lineno<TAB>text", one per line.
# Prints "location<TAB>lineno<TAB>token" for each record whose text contains a token
# hashing into the denylist; records skip themselves when they carry oem-allow:,
# unless --ignore-allow is passed (used by the guard's self-scan test, which must see
# marked lines too — erring strict, never lenient).
# The program is passed as an ARGUMENT (-c), never via stdin: stdin carries the
# records, and a heredoc-fed program would silently swallow them (caught live,
# 2026-08-24, by the block-then-allow demonstration).
hashed_offenders() {
  python3 -c "$(cat <<'PY'
import hashlib
import re
import sys

# '<length> <sha256>' pairs: prefix entries grouped by length, so each token is
# tested at each entry length it can reach.
by_length = {}
with open(sys.argv[1], encoding="utf-8") as fh:
    for line in fh:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        length_s, digest = line.split()
        by_length.setdefault(int(length_s), set()).add(digest)
lengths = sorted(by_length)

honour_allow = "--ignore-allow" not in sys.argv
token_re = re.compile(r"[A-Za-z0-9][A-Za-z0-9_-]*")
for record in sys.stdin:
    record = record.rstrip("\n")
    if not record:
        continue
    location, lineno, text = record.split("\t", 2)
    if honour_allow and "oem-allow:" in text:
        continue
    matched = False
    for token in token_re.findall(text):
        lowered = token.lower()
        for length in lengths:
            if length > len(lowered):
                break
            if hashlib.sha256(lowered[:length].encode()).hexdigest() in by_length[length]:
                print(f"{location}\t{lineno}\t{token}")
                matched = True
                break
        if matched:
            break
PY
)" "$HASHES" "${1:-}"
}

report_hashed() {  # stdin: hashed_offenders output; reports and counts them
  local location lineno token
  while IFS=$'\t' read -r location lineno token; do
    [ -z "$location" ] && continue
    printf '  BLOCKED  %s:%s\n           hashed-denylist token: %s\n' \
      "$location" "$lineno" "$token"
    hits=$((hits + 1))
  done
}

scan_staged() {
  local path="" lineno=0 line text records
  records=$(mktemp)
  while IFS= read -r line; do
    case "$line" in
      '+++ b/'*)
        path="${line#+++ b/}"
        # New or renamed PATHS are scanned like content; see scan_tracked on why a
        # filename gets no oem-allow escape.
        printf '(staged path)\t-\t%s\n' "$path" >> "$records" ;;
      '@@'*)     lineno=$(printf '%s' "$line" | sed -n 's/^@@ -[0-9,]* +\([0-9]*\).*/\1/p') ;;
      '+'*)
        text="${line#+}"
        printf '%s\t%s\t%s\n' "$path" "${lineno:-?}" "$text" >> "$records"
        lineno=$(( ${lineno:-0} + 1 )) ;;
      ' '*) lineno=$(( ${lineno:-0} + 1 )) ;;
    esac
  done < <(git -C "$REPO" diff --cached --unified=0 --no-color -- . 2>/dev/null)
  report_hashed < <(hashed_offenders < "$records")
  rm -f "$records"
}

scan_tracked() {
  local path hit lineno text records
  records=$(mktemp)
  while IFS= read -r path; do
    # The PATH is scanned as well as the contents: a pack file named after a maker,
    # with clean contents, is the likeliest shape for an un-authorised name to
    # re-enter. A filename cannot carry an oem-allow marker, deliberately: a tracked
    # path that needs an identifier in its NAME has no legitimate form here.
    printf '(tracked path)\t-\t%s\n' "$path" >> "$records"
    [ -f "$REPO/$path" ] || continue
    while IFS= read -r hit; do
      [ -z "$hit" ] && continue
      lineno="${hit%%:*}"; text="${hit#*:}"
      note_allowed "$path" "$lineno" "$text"
    done < <(grep -nI 'oem-allow:' "$REPO/$path" 2>/dev/null)
    awk -v p="$path" '{printf "%s\t%d\t%s\n", p, NR, $0}' "$REPO/$path" >> "$records" 2>/dev/null
  done < <(git -C "$REPO" ls-files)
  report_hashed < <(hashed_offenders < "$records")
  rm -f "$records"
}

# --message <file>: the commit-msg hook's mode. Git's own comment lines, and everything
# below a `--verbose` scissors line, are not the message and never reach history, so they
# are dropped before the scan rather than reported as offenders.
scan_message() {
  local file="${1:-}" body line lineno=0
  [ -n "$file" ] || { echo "check-identity: --message needs a file" >&2; exit 2; }
  [ -f "$file" ] || { echo "check-identity: no message file at $file" >&2; exit 2; }
  body=$(sed '/^#.*>8/,$d' "$file" | grep -v '^#')
  printf '%s' "$body" | grep -q 'oem-allow:' && return 0
  local records
  records=$(mktemp)
  while IFS= read -r line; do
    lineno=$((lineno + 1))
    printf '%s\t%s\t%s\n' "(commit message)" "$lineno" "$line" >> "$records"
  done <<< "$body"
  report_hashed < <(hashed_offenders < "$records")
  rm -f "$records"
}

# --file <path> [--ignore-allow]: scan ONE nominated file through the same matcher.
# Exists so a test (or the scheduled audit, or the generator's collision sweep) can apply
# the REAL matcher to a file without reimplementing it: a second copy of the matcher is
# this repo's named enemy. --ignore-allow disables the oem-allow exemption, so marked
# lines are scanned like any other — it errs STRICT: it can only add findings, never
# hide one. This mode scans what it is given and nothing else; it is not a substitute
# for the tracked scan and no hook calls it (both hooks call fixed modes).
scan_file() {
  local file="${1:-}" strict="${2:-}" records
  [ -n "$file" ] || { echo "check-identity: --file needs a path" >&2; exit 2; }
  [ -f "$file" ] || { echo "check-identity: no file at $file" >&2; exit 2; }
  if [ -n "$strict" ] && [ "$strict" != "--ignore-allow" ]; then
    echo "check-identity: unknown option '$strict' (only --ignore-allow)" >&2; exit 2
  fi
  records=$(mktemp)
  printf '(file path)\t-\t%s\n' "$file" >> "$records"
  awk -v p="$file" '{printf "%s\t%d\t%s\n", p, NR, $0}' "$file" >> "$records"
  report_hashed < <(hashed_offenders "$strict" < "$records")
  rm -f "$records"
}

# --history [<range>]: commit MESSAGES already in history, default every ref. Reports the
# SHA and the tokens, not the message text, so the purge list is exact without restating
# what is being purged. This mode carries NO exemptions of its own: the known-offender
# baseline lives in tests/test_repo_identity.py, where it is visible and can empty.
scan_history() {
  local range="${1:---all}" sha body hashed
  while IFS= read -r sha; do
    [ -z "$sha" ] && continue
    body=$(git -C "$REPO" log -1 --format='%B' "$sha")
    printf '%s' "$body" | grep -q 'oem-allow:' && continue
    hashed=$(printf '%s\n' "$body" | awk -v s="$sha" '{printf "%s\t%d\t%s\n", s, NR, $0}' | hashed_offenders)
    if [ -n "$hashed" ]; then
      printf '  BLOCKED  %s\n           hashed-denylist token(s): %s\n' "$sha" \
        "$(printf '%s\n' "$hashed" | cut -f3 | sort -u | tr '\n' ' ')"
      hits=$((hits + 1))
    fi
  done < <(git -C "$REPO" log --format='%H' $range 2>/dev/null)
}

[ -d "$REPO/.git" ] || { echo "check-identity: no repo at $REPO" >&2; exit 2; }

case "${1:-tracked}" in
  --staged)  scan_staged ;;
  --message) scan_message "${2:-}" ;;
  --history) scan_history "${2:---all}" ;;
  --file)    scan_file "${2:-}" "${3:-}" ;;
  tracked)   scan_tracked ;;
  *) echo "usage: check-identity.sh [--staged | --message <file> | --history [<range>] | --file <path> [--ignore-allow]]" >&2
     exit 2 ;;
esac

if [ "$allowed" -gt 0 ]; then
  echo
  echo "  $allowed oem-allow exemption(s), enumerated rather than exempted silently:"
  printf '%s' "$ALLOWED_LINES"
fi

if [ "$hits" -gt 0 ]; then
  echo
  echo "  $hits offender(s). Clean at creation is cheaper than a history purge afterwards."
  echo "  If an identifier is genuinely needed (e.g. a test asserting its absence), mark the"
  echo "  line:  oem-allow: <reason>"
  echo "  In a commit message that marker is a trailer and covers the whole message."
  echo "  If you believe a blocked token is INNOCENT: the denylist matches by hashed prefix,"
  echo "  and an entry needs lengthening. The editable source is"
  echo "  tools/identity-denylist-private.txt — gitignored, so it lives on the maintaining"
  echo "  machine and is absent from clones BY DESIGN (that absence is expected, not broken)."
  echo "  A fresh clone starts from tools/identity-denylist-private.example.txt."
  exit 1
fi
echo "  clean: no denylisted identifiers (OEM, customer or person, matched hashed)."
exit 0
