#!/usr/bin/env bash
# generate-identity-hashes.sh — regenerate the TRACKED hashed denylist from the
# PRIVATE plaintext source, refusing to write a denylist that would misfire.
#
# The hashed denylist holds tokens the guard must block without naming: a real
# maker is named only once it has authorised that use, and a guard that names
# what it blocks would itself be the leak. Since 2026-08-24 the SAME treatment
# covers the part-number, model and person categories, so no category of the
# denylist is readable in the tracked tree. A hashed list cannot be read by
# a human, so the EDITABLE source is private and gitignored
# (tools/identity-denylist-private.txt, one token per line, # for comments) and
# this script GENERATES the tracked file from it. Nobody hand-maintains the
# tracked half, so it cannot drift. A starting point ships as
# tools/identity-denylist-private.example.txt; copy it and edit.
#
# MATCHING IS BY PREFIX: an entry blocks every token that starts with it, so
# open-ended families (part-number stems, model families) need one entry, not
# an enumeration. Output format: "<length> <sha256>" per line — the scanner
# hashes each token's prefix at each listed length. Exposing lengths reveals
# nothing useful and keeps the scan cheap.
#
# THE FLOOR: entries shorter than 5 characters are REFUSED, loudly and
# non-zero — a short prefix blocks half the vocabulary. 5 rather than the
# proposed 6 because two live entries are exactly 5. An entry that genuinely
# cannot reach 5 characters (an open-ended short stem like a 3-letter model
# family) may carry "# floor-exception: <reason>" on its own line; the
# exception admits it past the floor and NOTHING ELSE — it is swept like every
# other entry, every generation.
#
# THE COLLISION SWEEP, hard-fail, every entry, every generation. A real
# collision stopping regeneration until it is resolved is chosen deliberately.
# Before the tracked file is replaced, the CANDIDATE
# denylist is run against the repo's tracked tree via the guard itself
# (check-identity.sh with IDENTITY_HASHES pointing at the candidate), so the
# sweep uses the REAL matcher, not a copy. Any hit outside oem-allow-marked
# lines is a collision, an entry that would block something already
# legitimately tracked, and generation REFUSES until it is resolved
# (lengthen the entry, or deal with the colliding token).
#
# WHAT THE SWEEP IS, AND IS NOT: it is pre-flight diagnostics for the moment
# an entry is added or changed, naming the collision as a collision. It is NOT
# the continuous check, and carries no such burden: the tracked scan runs over
# every tracked file inside tests/test_repo_identity.py, so an innocent
# colliding token entering the tree LATER is caught by the suite on every run
# (and by the pre-commit hook at creation), not only at the next regeneration.
#
# THE SIBLING is reported, never failed on. Set IDENTITY_SIBLING to a private
# consumer repo that legitimately carries the real vocabulary, and its hits are
# a preview of what would be blocked if that vocabulary migrated into the
# guarded tree. Unset by default, and when the sibling is not reachable that is
# SAID rather than half swept silently.
#
# Normalisation contract, shared with check-identity.sh: lowercase, strip,
# sha256 of the prefix. Entries must be single tokens (no spaces).
#
# Usage: generate-identity-hashes.sh
# Exit 0 written, 1 collision refused, 2 no private source / entry below the
# floor without an exception marker.

set -uo pipefail

REPO="${HARNESS_REPO:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
SRC="${IDENTITY_PRIVATE:-$REPO/tools/identity-denylist-private.txt}"
OUT="${IDENTITY_HASHES:-$REPO/tools/identity-denylist.hashes}"
GUARD="$REPO/tools/check-identity.sh"
SIBLING="${IDENTITY_SIBLING:-}"
FLOOR=5

if [ ! -f "$SRC" ]; then
  echo "generate-identity-hashes: no private source at $SRC" >&2
  echo "Create it (one token per line, gitignored) before generating." >&2
  exit 2
fi

# --- build the candidate ----------------------------------------------------------
candidate=$(mktemp)
{
  echo "# GENERATED by tools/generate-identity-hashes.sh — do not edit by hand."
  echo "# '<length> <sha256>' of each normalised (lowercased, stripped) PREFIX entry"
  echo "# in the PRIVATE, gitignored source. An entry blocks every token starting"
  echo "# with it. The plaintext never enters tracked core; edit the private source"
  echo "# and regenerate. See tools/check-identity.sh."
  python3 -c "$(cat <<'PY'
import hashlib
import sys

floor = int(sys.argv[2])
entries = set()
with open(sys.argv[1], encoding="utf-8") as fh:
    for lineno, raw in enumerate(fh, 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        token, _, comment = line.partition("#")
        token = token.strip().lower()
        if not token:
            continue
        if len(token) < floor and "floor-exception:" not in comment:
            print(
                f"generate-identity-hashes: REFUSED — entry at line {lineno} is "
                f"{len(token)} character(s), below the floor of {floor}, with no "
                "floor-exception marker. A short prefix blocks half the "
                "vocabulary; either lengthen it or mark the line "
                "'# floor-exception: <reason>' (it is still swept for "
                "collisions on every generation).",
                file=sys.stderr,
            )
            sys.exit(2)
        entries.add((len(token), hashlib.sha256(token.encode()).hexdigest()))
for length, digest in sorted(entries):
    print(length, digest)
PY
)" "$SRC" "$FLOOR"
} > "$candidate" || { rm -f "$candidate"; exit 2; }

# --- the collision sweep, against core, hard-fail ---------------------------------
sweep=$(IDENTITY_HASHES="$candidate" bash "$GUARD" 2>&1)
if [ $? -ne 0 ]; then
  echo "generate-identity-hashes: REFUSED — the candidate denylist collides with" >&2
  echo "the repo's tracked tree. An entry would block something already legitimately" >&2
  echo "tracked; lengthen the entry or resolve the colliding token, then retry." >&2
  echo "The guard's report of the collision(s):" >&2
  printf '%s\n' "$sweep" | grep -A1 'BLOCKED' >&2
  rm -f "$candidate"
  exit 1
fi

# --- the sibling, reported never failed on ----------------------------------------
if [ -n "$SIBLING" ] && [ -d "$SIBLING/.git" ]; then
  sibling_hits=$(IDENTITY_HASHES="$candidate" HARNESS_REPO="$SIBLING" bash "$GUARD" 2>/dev/null | grep -c 'BLOCKED' || true)
  echo "generate-identity-hashes: sibling report — $sibling_hits hit(s) in $SIBLING"
  echo "  (expected: the private consumer legitimately holds this vocabulary; the"
  echo "  count previews what would be blocked if it migrated into the guarded tree)"
else
  echo "generate-identity-hashes: sibling NOT swept — set IDENTITY_SIBLING to one" >&2
  echo "  (stated rather than half-swept silently; the guarded tree itself was" >&2
  echo "  swept in full)" >&2
fi

mv "$candidate" "$OUT"
count=$(grep -cv '^#' "$OUT" || true)
echo "generate-identity-hashes: wrote $count hash(es) to $OUT"
